server:
  port: 0

spring:
  application:
    name: map-service   # ? Config Server?? ?? ??

  profiles:
    active: default             # ? ??? profile

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/strayanimal?serverTimezone=Asia/Seoul
    username: stray
    password: stray
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


imagePath:
  url: C:\stray_image
