server:
  port: 0

spring:
  application:
    name: scheduler-service   # ⭐ Config Server에서 찾을 이름

  profiles:
    active: default             # ⭐ 가져올 profile

  config:
    import: optional:configserver:http://localhost:8888

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always # 개발용, 운영 시 never 권장
      platform: mysql

  datasource:
    url: jdbc:mysql://localhost:3306/strayanimal?serverTimezone=Asia/Seoul
    username: stray
    password: stray
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


imagePath:
  url: C:\stray_image