server:
  # google cloud는 port가 8080 고정임
  # local 개발이나, 데이터 받아올 때는 8000을 사용하자.
  port: 8000

spring:
  application:
    name: gateway-service   # ⭐ Config Server에서 찾을 이름

  profiles:
    active: default             # ⭐ 가져올 profile

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              "[/**]":
                allowed-origins:
                  - "https://nyangmong.com"
                  - "http://localhost:5173"
                allowed-methods:
                  - GET
                  - POST
                  - DELETE
                  - PATCH
                  - PUT
                  - OPTIONS
                allowed-headers:
                  - Content-Type
                  - Authorization
                  - X-Requested-With
                allow-credentials: true
          routes:
            - id: scheduler-service
              uri: lb://SCHEDULER-SERVICE
              # k8s 클러스터 내에서 다른 서비스를 지목하기 위한 DNS 명령 규칙
              # <service-name>.<namespace>.svc.cluster.local:port 번호
              #uri: http://user-service.default.svc.cluster.local:8081
              predicates:
                - Path=/scheduler-service/**
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/scheduler-service/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter

            - id: pet-service
              uri: lb://PET-SERVICE
              # k8s 클러스터 내에서 다른 서비스를 지목하기 위한 DNS 명령 규칙
              # <service-name>.<namespace>.svc.cluster.local:port 번호
              #uri: http://user-service.default.svc.cluster.local:8081
              predicates:
                - Path=/pet-service/**
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/pet-service/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter

            - id: map-service
              uri: lb://MAP-SERVICE
              # k8s 클러스터 내에서 다른 서비스를 지목하기 위한 DNS 명령 규칙
              # <service-name>.<namespace>.svc.cluster.local:port 번호
              #uri: http://user-service.default.svc.cluster.local:8081
              predicates:
                - Path=/map-service/**
              filters:
                - RemoveRequestHeader=Cookie
                - RewritePath=/map-service/(?<segment>.*), /$\{segment}
                - AuthorizationHeaderFilter